DROP DATABASE IF EXISTS symptomservice ;
DROP USER IF EXISTS `symptom_service`@`%`;
CREATE DATABASE IF NOT EXISTS symptomservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `symptom_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `symptomservice`.* TO `symptom_service`@`%`;
FLUSH PRIVILEGES;